public class Employee {

    public Id id{get;}
    public String name {get;}
    public String kana {get;}
    public String code {get;}

    public Date hireDate {get;}
    public Date retirementDate {get;}
    public GroupMaster belongGroup {get;}

    public URL image {get;}
    public URL twitter {get;}
    public URL youTube {get;}
    public String fanNickname {get;}

    public Employee() {
    }
}